name: rei
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_rei:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  file_picker: ^10.2.0
  path: ^1.9.1
  watcher: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
