// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `actual_line_len`, `update_line_lengths`, `update_single_line_length`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Buffer>>
abstract class Buffer implements RustOpaqueInterface {
  int get version;

  set version(int version);

  int byteOfLine({required int row});

  (int, int) idxToRowColumn({required int idx});

  (int, int) insert({
    required int row,
    required int column,
    required String text,
  });

  int lineCount();

  int lineCountWithTrailingNewline();

  int lineLen({required int row});

  int maxLineLength();

  factory Buffer() => RustLib.instance.api.crateApiBufferBufferNew();

  (int, int) removeChar({required int row, required int column});

  (int, int) removeRange({
    required int startRow,
    required int startColumn,
    required int endRow,
    required int endColumn,
  });

  int rowColumnToIdx({required int row, required int column});

  String textInRange({
    required int startRow,
    required int startColumn,
    required int endRow,
    required int endColumn,
  });

  @override
  String toString();
}
