// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Buffer>>
abstract class Buffer implements RustOpaqueInterface {
  int get version;

  set version(int version);

  (int, int) idxToRowColumn({required int idx});

  (int, int) insert({
    required int row,
    required int column,
    required String text,
  });

  int lineCount();

  int lineLen({required int row});

  factory Buffer() => RustLib.instance.api.crateApiBufferBufferNew();

  (int, int) removeChar({required int row, required int column});

  int rowColumnToIdx({required int row, required int column});

  @override
  String toString();
}
