// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Cursor {
  final int row;
  final int column;
  final int stickyColumn;

  const Cursor.raw({
    required this.row,
    required this.column,
    required this.stickyColumn,
  });

  static Cursor default_() =>
      RustLib.instance.api.crateApiCursorCursorDefault();

  factory Cursor({
    required int row,
    required int column,
    required int stickyColumn,
  }) => RustLib.instance.api.crateApiCursorCursorNew(
    row: row,
    column: column,
    stickyColumn: stickyColumn,
  );

  @override
  int get hashCode => row.hashCode ^ column.hashCode ^ stickyColumn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cursor &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          column == other.column &&
          stickyColumn == other.stickyColumn;
}
