// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'cursor.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

@freezed
@meta.immutable
sealed class Cursor with _$Cursor {
  const Cursor._();
  const factory Cursor.raw({
    required int row,
    required int column,
    required int stickyColumn,
  }) = _Cursor;
  static Cursor default_() =>
      RustLib.instance.api.crateApiCursorCursorDefault();

  factory Cursor({
    required int row,
    required int column,
    required int stickyColumn,
  }) => RustLib.instance.api.crateApiCursorCursorNew(
    row: row,
    column: column,
    stickyColumn: stickyColumn,
  );
}
