// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cursor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'selection.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

@freezed
@meta.immutable
sealed class Selection with _$Selection {
  const Selection._();
  const factory Selection.raw({required Cursor start, required Cursor end}) =
      _Selection;
  static Selection default_() =>
      RustLib.instance.api.crateApiSelectionSelectionDefault();

  bool isEmpty() =>
      RustLib.instance.api.crateApiSelectionSelectionIsEmpty(that: this);

  factory Selection({required Cursor start, required Cursor end}) => RustLib
      .instance
      .api
      .crateApiSelectionSelectionNew(start: start, end: end);

  Selection normalized() =>
      RustLib.instance.api.crateApiSelectionSelectionNormalized(that: this);
}
